/*


MAKE PLAYER LOOK IN MOUSE DIRECTION WITHOUT RAYCAST             
USE CINEMACINE CAMERAS FOR GAMEPLAY                             DONE
MAKE PHYSICAL BULLETS NO RAYCAST                                DONE
ADJUST ENEMIES ENGAGE RANGE TO BE GREATER THAN WEAPONS RANGE    
MAKE ENYMIES CHASE THE PLAYER                                   DONE
MAKE ENEMIES STOP FOLLWING WHEN THE PLAYER IS FAR ENOUGH        DONE
MAKE ENEMIES GO BACK TO THEIR POSITION AFTER A COUPLE SECS      DONE
MAKE ENEMIES CHARGE AT THE PLAYER WHEN IN RANGE                 
MAKE THE MAP LARGER TO ADJUST SOME VALUES                       
LEARN HOW TO MAKE A SPLASH SHADER                               
MAKE DIFFERENT WEAPONS FOR THE PLAYER TO USE                    
ADD SAUSE GRENADES TO THE PLAYER                                
LET THE PLAYER HAVE UP TO TWO WEAPONS AT THE TIME               
MAKE THE GRENADES RECHARGE OVER TIME                            

*/